web:
  image: nginx
  volumes:
    - ./templates:/etc/nginx/templates
    - /data/certs:/etc/nginx/certs
  ports:
    - "80:80"
    - "443:443"
  environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80